version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
  test:
    build: .
    command: rspec spec
    environment:
      RACK_ENV: test
      RAILS_ENV: test
      DATABASE_HOST: db
    depends_on:
      - db
